[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino

; Velocidad del monitor serie
monitor_speed = 115200

; Descarga automática de librerías
lib_deps = 
	jgromes/RadioLib @ ^6.3.0
	emelianov/modbus-esp8266 @ ^4.1.0
	adafruit/Adafruit SSD1306 @ ^2.5.9
	adafruit/Adafruit GFX Library @ ^1.11.9

; Optimizaciones para el chip ESP32-S3
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1